[Veego 1315] Update pipelines to publish changelogs
veegoteam/workflows pull request #27
Opened 2023-02-20 19:25 UTC by teymurgahramanov

2023-02-21 07:41 UTC, denis-osochenko requested changes
Pls see last commets

2023-02-21 07:41 UTC, denis-osochenko commented on .github/workflows/create-java-github-release.yml
> +            -e PASSWORD="ATATT3xFfGF0TDynfG3ieNEBdxrVFmw8bY576_EVJ1aG9as2_w16IPe8sJpV9zG2qql0WuP_g2kjQJ3FO4uOMR8h7mK8cB4OCn6qJ4ddr155FViyBR4hk0huzAjhNAPfVJxD1UYOH_ejqNs8kCPMAcwR7fY5x9qgz_AK9y7763Jz0G
Can we store password in secrets?

2023-02-21 07:41 UTC, denis-osochenko commented on .github/workflows/create-java-github-release.yml
> +            -e SPACE_KEY="GEN" \
It should be a pipeline variable with default value `GEN`

2023-02-21 07:41 UTC, denis-osochenko commented on .github/workflows/create-java-github-release.yml
> +            -e ANCESTOR_ID="1983676417" \
This should be configurable

2023-02-21 07:41 UTC, denis-osochenko commented on .github/workflows/create-java-github-release.yml
> +            -e ORPHAN_REMOVAL_STRATEGY="REMOVE_ORPHANS" \
Let's make these parameters configurable as well with default values as it set here

2023-02-21 07:45 UTC, teymurgahramanov commented on .github/workflows/create-java-github-release.yml
> +            -e PASSWORD="ATATT3xFfGF0TDynfG3ieNEBdxrVFmw8bY576_EVJ1aG9as2_w16IPe8sJpV9zG2qql0WuP_g2kjQJ3FO4uOMR8h7mK8cB4OCn6qJ4ddr155FViyBR4hk0huzAjhNAPfVJxD1UYOH_ejqNs8kCPMAcwR7fY5x9qgz_AK9y7763Jz0G
Sure, its temporary solution for test purpose. Later it will be replaced with dedicated user and secret will be stored as shared organization secret

2023-02-21 08:01 UTC, teymurgahramanov commented on .github/workflows/create-java-github-release.yml
> +            -e SPACE_KEY="GEN" \
Done

2023-02-21 08:01 UTC, teymurgahramanov commented on .github/workflows/create-java-github-release.yml
> +            -e ANCESTOR_ID="1983676417" \
Done

2023-02-21 08:01 UTC, teymurgahramanov commented on .github/workflows/create-java-github-release.yml
> +            -e ORPHAN_REMOVAL_STRATEGY="REMOVE_ORPHANS" \
Done

2023-02-28 10:52 UTC, denis-osochenko commented on .github/workflows/create-changelog.yml
> +        description: "From which version start to building changelog"
```suggestion
        description: "From which version start building changelog"
```

2023-02-28 10:53 UTC, denis-osochenko commented on .github/workflows/create-changelog.yml
> +        required: true
```suggestion
        required: false
```
And let's a default empty value

2023-02-28 11:58 UTC, merged