Redesigned workflow
veegoteam/workflows pull request #38
Opened 2023-05-15 09:18 UTC by teymurgahramanov

2023-05-15 10:13 UTC, corest requested changes
replace all `_` with `-` in action inputs

e.g.
```
artifact_name
```
to
```
artifact-name
```

2023-05-15 10:15 UTC, corest commented on actions/push-image/action.yml
> +name: build-push-image
split this into two separate actions for was and for azure
for AWS we will use two different accounts for now
and Azure eventually will be removed

But no need to mix everything in the same action

2023-05-17 13:04 UTC, teymurgahramanov commented on actions/push-image/action.yml
> +name: build-push-image
These two actions are almost the same. I don't see the reason for duplicating.

2023-05-19 07:09 UTC, teymurgahramanov commented on actions/push-image/action.yml
> +name: build-push-image
Done

2023-05-19 07:56 UTC, closed without merging